# Generated by Django 5.2.4 on 2025-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
